version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - gomod
      - dependencies
    reviewers:
      - nimnest/dependabot-reviewers
